### ISSUE TITLE
Modules to be updated (for 7.x-2.23)

### ISSUE THREAD

**Issue by tobybellwood** [govCMS/GovCMS7#529]
The following is a tracking list of all modules that have available updates as of 1 September 2018 (post 7.x-2.22)
Live list at https://www.drupal.org/project/govcms/releases/7.x-2.22

- [ ] Update [accessible_forms](https://www.drupal.org/project/accessible_forms) to 7.x-1.0-alpha2 (from 7.x-1.0-alpha1)
- [x] #609 Update [search_api_acquia](https://www.drupal.org/project/search_api_acquia) to 7.x-2.4 (from 7.x-2.3)
- [x] #564 Update [addressfield](https://www.drupal.org/project/addressfield) to 7.x-1.2 (from 7.x-1.1)
- [x] #565 Update [breakpoints](https://www.drupal.org/project/breakpoints) to 7.x-1.6 (from 7.x-1.3)
- [x] #567 Update [ccl](https://www.drupal.org/project/ccl) to 7.x-1.6 (from 7.x-1.5)
- [x] #532 Update [context](https://www.drupal.org/project/context) to 7.x-3.7 (from 7.x-3.6)
- [x] #568 Update [crumbs](https://www.drupal.org/project/crumbs) to 7.x-2.7 (from 7.x-2.3)
- [ ] Update [ctools](https://www.drupal.org/project/ctools) to 7.x-1.14 (from 7.x-1.12)
- [x] #553 Update [date](https://www.drupal.org/project/date) to 7.x-2.10 (from 7.x-2.9)
- [ ] Update [defaultconfig](https://www.drupal.org/project/defaultconfig) to 7.x-1.0-alpha11 (from 7.x-1.0-alpha9)
- [x] #569 Update [diff](https://www.drupal.org/project/diff) to 7.x-3.3 (from 7.x-3.2)
- [x] #594 Update [entitycache](https://www.drupal.org/project/entitycache) to 7.x-1.5 (from 7.x-1.2) (notes in #423)
- [x] #535 Update [event_log](https://www.drupal.org/project/event_log) to 7.x-1.6 (from 7.x-1.4)
- [x] #570 Update [features](https://www.drupal.org/project/features) to 7.x-2.10 (from 7.x-2.9)
**BLOCKED** Update [feeds](https://www.drupal.org/project/feeds) to 7.x-2.0-beta4 (from 7.x-2.0-beta3) (notes in #582)
- [ ] Update [feeds_tamper](https://www.drupal.org/project/feeds_tamper) to 7.x-1.2 (from 7.x-1.1)
- [x] #614 Update [field_group](https://www.drupal.org/project/field_group) to 7.x-1.6 (from 7.x-1.5)
- [x] #694 Update [file_entity](https://www.drupal.org/project/file_entity) to 7.x-2.21 (from 7.x-2.12)
- [x] #558 Update [focal_point](https://www.drupal.org/project/focal_point) to 7.x-1.1 (from 7.x-1.0-beta4)
(Global Redirect)
- [ ] Update [hierarchical_select](https://www.drupal.org/project/hierarchical_select) to 7.x-3.0-beta8 (from 7.x-3.0-beta7)
- [ ] Update [honeypot](https://www.drupal.org/project/honeypot) to 7.x-1.24 (from 7.x-1.22)
- [x] #572 Update [image_link_formatter](https://www.drupal.org/project/image_link_formatter) to 7.x-1.1 (from 7.x-1.0)
(job scheduler)
- [x] #573 Update [link](https://www.drupal.org/project/link) to 7.x-1.5 (from 7.x-1.3)
- [x] #621 Update [linkchecker](https://www.drupal.org/project/linkchecker) to 7.x-1.3 (from 7.x-1.2)
- [x] #574 Update [login_destination](https://www.drupal.org/project/login_destination) to 7.x-1.4 (from 7.x-1.1)
- [x] #575 Update [menu_block](https://www.drupal.org/project/menu_block) to 7.x-2.7 (from 7.x-2.6)
- [x] #683 Update [metatag](https://www.drupal.org/project/metatag) to 7.x-1.25 (from 7.x-1.21)
- [ ] Update [minisite](https://www.drupal.org/project/minisite) to 7.x-1.0-alpha3 (from 7.x-1.0-alpha2)
- [x]  #577 Update [module_filter](https://www.drupal.org/project/module_filter) to 7.x-2.1 (from 7.x-2.0)
- [x] #595 Update [quicktabs](https://www.drupal.org/project/quicktabs) to 7.x-3.8 (from 7.x-3.6)
**BLOCKED** Update [redirect](https://www.drupal.org/project/redirect) to 7.x-1.0-rc3 (from 7.x-1.0-rc1) (notes in #241 #440)
- [x] #520 Update [robotstxt](https://www.drupal.org/project/robotstxt) to 7.x-1.4 (from 7.x-1.3)
- [x] #579 Update [rules](https://www.drupal.org/project/rules) to 7.x-2.11 (from 7.x-2.9)
- [ ] Update [services_views](https://www.drupal.org/project/services_views) to 7.x-1.3 (from 7.x-1.2)
- [x] #580 Update [site_map](https://www.drupal.org/project/site_map) to 7.x-1.3 (from 7.x-1.2)
- [x] #599 Update [spamspan](https://www.drupal.org/project/spamspan) to 7.x-1.3 (from 7.x-1.x)
- [x] #611 Update [toc_filter](https://www.drupal.org/project/toc_filter) to 7.x-1.3 (from 7.x-1.2)
- [x] #612 Update [token](https://www.drupal.org/project/token) to 7.x-1.7 (from 7.x-1.6)
- [x] #596 Update [username_enumeration_prevention](https://www.drupal.org/project/username_enumeration_prevention) to 7.x-1.2 (from 7.x-1.0)
- [x] #615 Update [video_filter](https://www.drupal.org/project/video_filter) to 7.x-3.4 (from 7.x-3.3)
- [x] #617 Update [viewfield](https://www.drupal.org/project/viewfield) to 7.x-2.1 (from 7.x-2.0)
- [x] #684 Update [views](https://www.drupal.org/project/views) to 7.x-3.20 (from 7.x-3.17) (notes in #550)
- [x] #619 Update [views_bulk_operations](https://www.drupal.org/project/views_bulk_operations) to 7.x-3.5 (from 7.x-3.3)
- [x] #598 Update [webform_phone](https://www.drupal.org/project/webform_phone) to 7.x-1.23 (from 7.x-1.21)
- [x] #620 Update [workbench_access](https://www.drupal.org/project/workbench_access) to 7.x-1.5 (from 7.x-1.4)
**BLOCKED** Update [workbench_moderation](https://www.drupal.org/project/workbench_moderation) to 7.x-3.0 (from 7.x-1.4) (notes in #376 #392) 
- [x] #600 Update [wysiwyg](https://www.drupal.org/project/wysiwyg) to 7.x-2.5 (from 7.x-2.x)
- [ ] Update [wysiwyg_filter](https://www.drupal.org/project/wysiwyg_filter) to 7.x-1.6-rc9 (from 7.x-1.6-rc2)
- [x] #608 Update [zen](https://www.drupal.org/project/zen) to 7.x-5.6 (from 7.x-5.5)

**Comment by rooby** [comment]
With the workbench update blocked, could we please revisit this: #597
